  version: 2.1
  jobs:
    build:
      machine: 
        image: ubuntu-1604:201903-01
      steps:
        - checkout 
        - run:
            name: 'requirements'
            command: |
            sudo apt-get -y -q update
            sudo apt-get install graphviz
            sudo apt-get install doxygen
            make
        - persist_to_workspace:
            root: ~/project
            paths:
              - terminal
              - test.txt
              - testresult.txt
              - test2.txt
              - saveto.txt
              - expected.txt
              - filesystem.txt
              
    output:
      machine:
        image: ubuntu-1604:201903-01
      steps:
        - attach_workspace:
            at: ~/project      
        - run:
            name: output
            command: ./terminal < test.txt
    output2:
      machine:
        image: ubuntu-1604:201903-01
      steps:
        - attach_workspace:
            at: ~/project      
        - run:
            name: output
            command: ./terminal < test2.txt
        - run:
            name: diff
            command: diff -bB expected.txt saveto.txt

    diff:
      machine:
        image: ubuntu-1604:201903-01
      steps:
        - attach_workspace:
            at: ~/project        
        - run:
            name: Diff
            command: ./terminal < test.txt > output diff output testresult.txt

    doxygen:
      machine:
        image: ubuntu-1604:201903-01
      steps:
        - attach_workspace:
            at: ~/project
        - run:
            name: 'Doxygen'
            command: |
              doxygen -g Doxyfile;
              doxygen Doxyfile;
        - store_artifacts:
            path: ./html
            
  workflows:
    version: 2
    build_print_diff:
      jobs:
        - build
        - output:
           requires:
            - build
        - output2:
           requires:
             - build
        - diff:
           requires:
             - output
             - build
        - doxygen:
           requires:
             - build

