  version: 2.1
  jobs:
    build:
      docker: 
        - image: patrikkocsis/modern:check-2.0
      steps:
        - checkout 
        - run:
            name: Cppcheck
            command: cppcheck --language=c++ --enable=performance *.cpp *.h
        - run:
            name: Make
            command: make
        - run:
            name: Valgrind
            command: valgrind --leak-check=full ./terminal < test.txt

    doxygen:
      docker:
        - image: patrikkocsis/modern:doxygen-2.0
      steps:
        - checkout   
        - run: doxygen Doxyfile
        - store_artifacts:
            path: ./html
                

  workflows:
    version: 2
    build_print_diff:
      jobs:
        - build
        - doxygen
