version: 2
jobs:
  build_and_test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'make'
      - run: ./projekt < test.txt > output.txt      
workflows:
  version: 2
  tasks:
    jobs:
      - build_and_test