  version: 2.1
  jobs:
    build:
      machine: 
        image: ubuntu-1604:201903-01
      steps:
        - checkout 
        - run:
            name: Requirements
            command: |
              sudo apt-get -y -q update
              sudo apt-get install graphviz
              sudo apt-get install doxygen
              sudo apt-get install texlive-latex-extra
          sudo apt-get install cppcheck
          sudo apt-get install valgrind
        - run:
            name: Cppcheck
            command: cppcheck --language=c++ --enable=performance *.cpp *.h
        - run:
            name: Make
            command: make
        - run:
            name: Valgrind
            command: valgrind --leak-check=full ./terminal < test.txt
        - run:
            name: 'Doxygen'
            command: |
              doxygen Doxyfile
              cd ./latex && make
        - store_artifacts:
            path: ./latex/refman.pdf
        - persist_to_workspace:
            root: ~/project
            paths:
              - terminal
              - test.txt
              - testresult.txt
              - test2.txt
              - saveto.txt
              - expected.txt
              - filesystem.txt

    output:
      machine:
        image: ubuntu-1604:201903-01
      steps:
        - attach_workspace:
            at: ~/project      
        - run:
            name: output
            command: ./terminal < test.txt

    output2:
      machine:
        image: ubuntu-1604:201903-01
      steps:
        - attach_workspace:
            at: ~/project      
        - run:
            name: output
            command: ./terminal < test2.txt
        - run:
            name: diff
            command: diff -bB expected.txt saveto.txt

    diff:
      machine:
        image: ubuntu-1604:201903-01
      steps:
        - attach_workspace:
            at: ~/project        
        - run:
            name: Diff
            command: ./terminal < test.txt > output diff output testresult.txt

  workflows:
    version: 2
    build_print_diff:
      jobs:
        - build
        - output:
           requires:
            - build
        - output2:
           requires:
             - build
        - diff:
           requires:
             - output
             - build

