  version: 2.1
  jobs:
    build:
      machine: 
        image: ubuntu-1604:201903-01
      steps:
        - checkout 
        - run: 'make'
        - persist_to_workspace:
            root: ~/project
            paths:
              - terminal
              - test.txt
              
    output:
      machine:
        image: ubuntu-1604:201903-01
      steps:
        - attach_workspace:
            at: ~/project      
        - run:
            name: output
            command: ./terminal < test.txt
            
  workflows:
    version: 2
    build_print_diff:
      jobs:
        - build
        - output:
           requires:
             - build